CHECKPOINT_LOADER_NAME = "CheckpointLoaderSimple"
UNET_LOADER_NAME = "UNETLoader"
CLIP_LOADER_NAME = "CLIPLoader"
VAE_LOADER_NAME = "VAELoader"
LORA_LOADER_NAME = "LoraLoader"

ALICE_LORA_STACK_TYPE = "ALICE_LORA_STACK"
